//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEFI_SyO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IDPrestamo { get; set; }
        public string IDLibro { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucionPrevista { get; set; }
        public Nullable<System.DateTime> FechaDevolucionReal { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
